keybinding:
  universal:
    prevItem-alt: 'e' # go one line up
    nextItem-alt: 'n' # go one line down
    nextMatch: 'k'
    prevMatch: 'K'
    new: 'k'
    edit: '!'
    scrollUpMain-alt1: 'E' # main panel scroll up
    scrollDownMain-alt1: 'N' # main panel scroll down
    moveDownCommit: '<c-n>' # move commit down one
    moveUpCommit: '<c-e>' # move commit up one
